[package]
name = "lao-eval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
lao-eval-api = { path = "../../api/eval", version = "0.1.0" }

[lints]
workspace = true

[package.metadata.lao]
kind = "svc"
owner = "A11"
api = "lao-eval-api"
state = "eval"
isolate = "worker"
status = "stub"
