[package]
name = "lao-train"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
lao-train-api = { path = "../../api/train", version = "0.1.0" }

[lints]
workspace = true

[package.metadata.lao]
kind = "svc"
owner = "A14"
api = "lao-train-api"
state = "train"
isolate = "worker"
status = "stub"
