[package]
name = "lao-route"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
candle-semantic-router = { version = "=0.3.0", default-features = false, features = ["accelerate"] }
lao-route-api = { path = "../../api/route", version = "0.1.0" }
serde_json.workspace = true

[lints]
workspace = true

[package.metadata.lao]
kind = "svc"
owner = "A08"
api = "lao-route-api"
state = "route"
isolate = "linked"
status = "draft"
