[package]
name = "lao-train-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
lao-train = { path = "../../svc/train", version = "0.1.0" }

[lints]
workspace = true

[package.metadata.lao]
kind = "app"
owner = "A14"
state = "none"
isolate = "process"
status = "stub"
