[package]
name = "lao-gate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
hyper.workspace = true
http-body-util.workspace = true
hyper-util.workspace = true
lao-gate-api = { path = "../../api/gate", version = "0.1.0" }
lao-route-api = { path = "../../api/route", version = "0.1.0" }
lao-run-api = { path = "../../api/run", version = "0.1.0" }
rustls.workspace = true
rustls-platform-verifier.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true

[lints]
workspace = true

[package.metadata.lao]
kind = "svc"
owner = "A03"
api = "lao-gate-api"
state = "none"
isolate = "linked"
status = "stub"
